### ISSUE TITLE
Can't resolve '@geut/swarm-hooks' 

### ISSUE THREAD

**Issue by moskalyk** [geut/swarm-hooks#3]
I use the same example from the README.md. The error I get is:

```
./src/App.js
Module not found: Can't resolve '@geut/swarm-hooks' in ...
```

**Comment by moskalyk** [comment]
resolves with 

```
yarn add @geut/swarm-hooks@1.0.0-beta.10 @geut/discovery-swarm-webrtc
```

**Comment by tinchoz49** [comment]
Hey @moskalyk, sorry, we forgot to put in the readme that @geut/discovery-swarm-webrtc is a `peerDependency` of @geut/swarm-hooks
